package MPD.service;

import MPD.config.AppSettings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.*;
import java.util.regex.*;

/**
 * Applies the browser-measured stream sync delay by writing a PipeWire
 * filter-chain virtual sink (fixed delay) and pointing MPD's PipeWire
 * output at it. This is the automatic equivalent of set-sync-delay.sh —
 * same mechanism, just driven by a measured value from the browser instead
 * of manual trial and error.
 * <p>
 * Why a delay sink instead of trying to reduce stream latency: HTTP audio
 * streaming has an unavoidable buffer (encoder + browser).
 * Rather than fighting that, local speakers are
 * delayed by the same amount so both listening points stay in sync with
 * each other, even though both are now slightly behind the actual MPD
 * playback position. Neither listener perceives this — sync between
 * them is what matters, not absolute latency to the source.
 */
@Service
public class AudioWatchService {

    private static final Logger log = LoggerFactory.getLogger(AudioWatchService.class);

    private static final String SINK_NAME = "webplayer-sync-sink";
    private static final Path PIPEWIRE_CONF_DIR =
        Path.of(System.getProperty("user.home"), ".config", "pipewire", "pipewire.conf.d");
    private static final Path PIPEWIRE_CONF = PIPEWIRE_CONF_DIR.resolve("53-webplayer-sync.conf");

    private final AppSettings settings;

    public AudioWatchService(AppSettings settings) {
        this.settings = settings;
    }
    
    public synchronized void applySyncDelay(double delaySeconds) throws IOException, InterruptedException {
        if (delaySeconds <= 0) {
            disableSyncDelay();
            return;
        }

        Files.createDirectories(PIPEWIRE_CONF_DIR);
        Files.writeString(PIPEWIRE_CONF, buildFilterChainConfig(delaySeconds));
        log.info("Wrote sync delay config: {}s → {}", delaySeconds, PIPEWIRE_CONF);

        restartPipewire();
        Thread.sleep(1500); // give PipeWire time to create the new sink

        pointMpdAtSyncSink();
        restartMpd();

        log.info("Sync delay of {}s applied — MPD now outputs to {}", delaySeconds, SINK_NAME);
    }

    private void disableSyncDelay() throws IOException, InterruptedException {
        Files.deleteIfExists(PIPEWIRE_CONF);
        removeMpdSinkOverride();
        restartPipewire();
        restartMpd();
        log.info("Sync delay disabled — MPD reverted to PipeWire's default sink");
    }

    // ── PipeWire config ───────────────────────────────────────────────────────

    private String buildFilterChainConfig(double delaySeconds) {
        return """
            # WebPlayer stream sync delay — %.1fs
            # Auto-generated by AudioWatchService — do not edit by hand,
            # it will be overwritten on the next calibration.
            context.modules = [
                { name = libpipewire-module-filter-chain
                  args = {
                      node.name         = "%s"
                      node.description  = "WebPlayer Sync (%.1fs delay)"
                      capture.props = {
                          media.class = "Audio/Sink"
                          node.name   = "%s"
                      }
                      playback.props = {
                          node.target = "@DEFAULT_SINK@"
                      }
                      filter.graph = {
                          nodes = [
                              { type    = builtin
                                name    = delay
                                label   = delay
                                control = { "Delay (s)" = %.2f } }
                          ]
                          inputs  = [ "delay:In L" "delay:In R" ]
                          outputs = [ "delay:Out L" "delay:Out R" ]
                      }
                  }
                }
            ]
            """.formatted(delaySeconds, SINK_NAME, delaySeconds, SINK_NAME, delaySeconds);
    }

    // ── MPD config editing ────────────────────────────────────────────────────

    private static final Pattern PIPEWIRE_BLOCK =
        Pattern.compile("(audio_output\\s*\\{[^}]*type\\s+\"pipewire\"[^}]*)}", Pattern.DOTALL);
    private static final Pattern SINK_LINE =
        Pattern.compile("\\n\\s*sink\\s+\"[^\"]*\"\\n");

    private void pointMpdAtSyncSink() throws IOException {
        editMpdConf(block -> {
            String stripped = SINK_LINE.matcher(block).replaceAll("\n");
            return stripped.stripTrailing() + "\n    sink      \"" + SINK_NAME + "\"\n}";
        });
    }

    private void removeMpdSinkOverride() throws IOException {
        editMpdConf(block -> {
            String stripped = SINK_LINE.matcher(block).replaceAll("\n");
            return stripped.stripTrailing() + "\n}";
        });
    }

    private void editMpdConf(java.util.function.Function<String, String> blockEditor) throws IOException {
        Path mpdConf = Path.of(AppSettings.expandHome("~/.config/mpd/mpd.conf"));
        if (!Files.exists(mpdConf))
            throw new IOException("mpd.conf not found at " + mpdConf);

        String content = Files.readString(mpdConf);
        Matcher m = PIPEWIRE_BLOCK.matcher(content);
        if (!m.find())
            throw new IOException("No 'type pipewire' audio_output block found in mpd.conf");

        String newBlock = blockEditor.apply(m.group(1));
        String newContent = content.substring(0, m.start()) + newBlock + content.substring(m.end());
        Files.writeString(mpdConf, newContent);
    }

    // ── Service restarts ──────────────────────────────────────────────────────

    private void restartPipewire() throws IOException, InterruptedException {
        exec("systemctl", "--user", "restart", "pipewire", "pipewire-pulse");
    }

    private void restartMpd() throws IOException, InterruptedException {
        exec("systemctl", "--user", "restart", "mpd");
    }

    private void exec(String... cmd) throws IOException, InterruptedException {
        Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
        try (var r = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
            while (r.readLine() != null) { /* discard */ }
        }
        p.waitFor();
    }
}
