package MPD.service;

import MPD.config.AppSettings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.*;
import java.net.Socket;
import java.nio.file.*;
import java.util.Locale;
import java.util.regex.*;

/**
 * Applies the browser-measured stream sync delay by writing a PipeWire
 * filter-chain virtual sink (fixed delay) and pointing MPD's PipeWire
 * output at it.
 * <p>
 * Every step that can silently no-op instead of failing loudly now has an
 * explicit verification: the sink's existence is confirmed via `pactl` before
 * MPD is pointed at it, and MPD's httpd port is polled until it accepts
 * connections before this method returns success — see the comments at each
 * check for the specific failure mode being guarded against.
 */
@Service
public class AudioWatchService {

    private static final Logger log = LoggerFactory.getLogger(AudioWatchService.class);

    private static final String SINK_NAME = "webplayer-sync-sink";
    private static final Path PIPEWIRE_CONF_DIR =
            Path.of(System.getProperty("user.home"), ".config", "pipewire", "pipewire.conf.d");
    private static final Path PIPEWIRE_CONF = PIPEWIRE_CONF_DIR.resolve("53-webplayer-sync.conf");

    private final AppSettings settings;

    public AudioWatchService(AppSettings settings) {
        this.settings = settings;
    }

    public synchronized void applySyncDelay(double delaySeconds) throws IOException, InterruptedException {
        if (delaySeconds <= 0) {
            disableSyncDelay();
            return;
        }

        Files.createDirectories(PIPEWIRE_CONF_DIR);
        Files.writeString(PIPEWIRE_CONF, buildFilterChainConfig(delaySeconds));
        log.info("Wrote sync delay config: {}s → {}", delaySeconds, PIPEWIRE_CONF);

        restartPipewire();
        
        if (!waitForSink(SINK_NAME, 5000)) {
            throw new IOException(
                    "PipeWire restarted but '" + SINK_NAME + "' never appeared. " +
                            "Check `journalctl --user -u pipewire -n 50` for a module load error " +
                            "(often a filter-chain config syntax issue on this PipeWire version)."
            );
        }

        pointMpdAtSyncSink();
        restartMpd();

        int httpPort = parseHttpdPort();
        if (httpPort > 0 && !waitForPort("localhost", httpPort, 8000)) {
            throw new IOException(
                    "MPD restarted but its HTTP stream on port " + httpPort +
                            " never came back up within 8s. It may still be starting — try again shortly."
            );
        }

        log.info("Sync delay of {}s applied and verified — MPD now outputs to {}", delaySeconds, SINK_NAME);
    }

    private void disableSyncDelay() throws IOException, InterruptedException {
        Files.deleteIfExists(PIPEWIRE_CONF);
        removeMpdSinkOverride();
        restartPipewire();
        restartMpd();
        log.info("Sync delay disabled — MPD reverted to PipeWire's default sink");
    }

    // ── PipeWire config ───────────────────────────────────────────────────────

    private String buildFilterChainConfig(double delaySeconds) {
        return String.format(Locale.ROOT, """
            # WebPlayer stream sync delay — %.1fs
            # Auto-generated by AudioWatchService — do not edit by hand,
            # it will be overwritten on the next calibration.
            context.modules = [
                { name = libpipewire-module-filter-chain
                  args = {
                      node.name         = "%s"
                      node.description  = "WebPlayer Sync (%.1fs delay)"
                      capture.props = {
                          media.class = "Audio/Sink"
                          node.name   = "%s"
                      }
                      playback.props = {
                          node.target = "@DEFAULT_SINK@"
                      }
                      filter.graph = {
                          nodes = [
                              { type    = builtin
                                name    = delay
                                label   = delay
                                control = { "Delay (s)" = %.2f } }
                          ]
                          inputs  = [ "delay:In L" "delay:In R" ]
                          outputs = [ "delay:Out L" "delay:Out R" ]
                      }
                  }
                }
            ]
            """, delaySeconds, SINK_NAME, delaySeconds, SINK_NAME, delaySeconds);
    }
    
    private boolean waitForSink(String sinkName, long timeoutMs) throws InterruptedException {
        long deadline = System.currentTimeMillis() + timeoutMs;
        while (System.currentTimeMillis() < deadline) {
            try {
                String out = execCapture("pactl", "list", "short", "sinks");
                if (out.contains(sinkName)) return true;
            } catch (IOException ignored) { /* pactl not ready yet, keep polling */ }
            Thread.sleep(300);
        }
        return false;
    }

    /** Polls a TCP port until it accepts a connection, or timeoutMs elapses. */
    private boolean waitForPort(String host, int port, long timeoutMs) throws InterruptedException {
        long deadline = System.currentTimeMillis() + timeoutMs;
        while (System.currentTimeMillis() < deadline) {
            try (Socket s = new Socket()) {
                s.connect(new java.net.InetSocketAddress(host, port), 500);
                return true;
            } catch (IOException ignored) { /* not listening yet */ }
            Thread.sleep(300);
        }
        return false;
    }

    /** Reads the httpd output's port from mpd.conf, or -1 if not found/parseable. */
    private int parseHttpdPort() {
        try {
            Path mpdConf = Path.of(AppSettings.expandHome("~/.config/mpd/mpd.conf"));
            String content = Files.readString(mpdConf);
            Matcher httpdBlock = Pattern.compile(
                    "audio_output\\s*\\{[^}]*type\\s+\"httpd\"[^}]*}", Pattern.DOTALL
            ).matcher(content);
            if (!httpdBlock.find()) return -1;
            Matcher portLine = Pattern.compile("port\\s+\"(\\d+)\"").matcher(httpdBlock.group());
            return portLine.find() ? Integer.parseInt(portLine.group(1)) : -1;
        } catch (Exception e) {
            return -1; // can't determine port — skip the readiness check rather than fail on it
        }
    }

    // ── MPD config editing ────────────────────────────────────────────────────

    private static final Pattern PIPEWIRE_BLOCK =
            Pattern.compile("(audio_output\\s*\\{[^}]*type\\s+\"pipewire\"[^}]*)}", Pattern.DOTALL);
    private static final Pattern SINK_LINE =
            Pattern.compile("\\n\\s*sink\\s+\"[^\"]*\"\\n");

    private void pointMpdAtSyncSink() throws IOException {
        editMpdConf(block -> {
            String stripped = SINK_LINE.matcher(block).replaceAll("\n");
            return stripped.stripTrailing() + "\n    sink      \"" + SINK_NAME + "\"\n}";
        });
    }

    private void removeMpdSinkOverride() throws IOException {
        editMpdConf(block -> {
            String stripped = SINK_LINE.matcher(block).replaceAll("\n");
            return stripped.stripTrailing() + "\n}";
        });
    }

    private void editMpdConf(java.util.function.Function<String, String> blockEditor) throws IOException {
        Path mpdConf = Path.of(AppSettings.expandHome("~/.config/mpd/mpd.conf"));
        if (!Files.exists(mpdConf))
            throw new IOException("mpd.conf not found at " + mpdConf);

        String content = Files.readString(mpdConf);
        Matcher m = PIPEWIRE_BLOCK.matcher(content);
        if (!m.find())
            throw new IOException(
                    "No 'type \"pipewire\"' audio_output block found in mpd.conf. " +
                            "Sync delay requires that output to be present and configured."
            );

        String newBlock = blockEditor.apply(m.group(1));
        String newContent = content.substring(0, m.start()) + newBlock + content.substring(m.end());
        Files.writeString(mpdConf, newContent);
    }

    // ── Service restarts ──────────────────────────────────────────────────────

    private void restartPipewire() throws IOException, InterruptedException {
        exec("systemctl", "--user", "restart", "pipewire", "pipewire-pulse");
    }

    private void restartMpd() throws IOException, InterruptedException {
        exec("systemctl", "--user", "restart", "mpd");
    }

    private void exec(String... cmd) throws IOException, InterruptedException {
        Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
        try (var r = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
            while (r.readLine() != null) { /* discard */ }
        }
        p.waitFor();
    }

    private String execCapture(String... cmd) throws IOException {
        Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
        String out;
        try (var r = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
            out = r.lines().reduce("", (a, b) -> a + "\n" + b);
        }
        try { p.waitFor(); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
        return out;
    }
}